<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd"
             schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>async_pupil_wrapper</name>
  <version>0.0.0</version>
  <description>ROS2 wrapper for Pupil Labs Async Realtime API</description>
  <maintainer email="olgamelnik12@gmail.com">olhamelnyk</maintainer>
  <license>Apache-2.0</license>

  <!-- Build-Tool für ament_python-Packages -->
  <buildtool_depend>ament_python</buildtool_depend>

  <!-- Test-Dependencies -->
  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <!-- Message-Generierung -->
  <build_depend>rosidl_default_generators</build_depend>

  <!-- ROS2 Python-Client -->
  <build_depend>rclpy</build_depend>
  <exec_depend>rclpy</exec_depend>

  <!-- Standard ROS-Messages -->
  <build_depend>std_msgs</build_depend>
  <exec_depend>std_msgs</exec_depend>
  <build_depend>sensor_msgs</build_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <build_depend>blink_interface</build_depend>
  <exec_depend>blink_interface</exec_depend>
  <build_depend>imu_interface</build_depend>
  <exec_depend>imu_interface</exec_depend>

  <!-- OpenCV Bridge -->
  <build_depend>cv_bridge</build_depend>
  <exec_depend>cv_bridge</exec_depend>

  <!-- Laufzeit für generierte Nachrichten -->
  <exec_depend>rosidl_default_runtime</exec_depend>

  <!-- Externe Python-Bibliothek -->
  <build_depend>pupil-labs-realtime-api</build_depend>
  <exec_depend>pupil-labs-realtime-api</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
